name: ocelapp
channels:
  - defaults
dependencies:
  - python=3.10.9
  - flask=2.2.2
  - pip=22.3.1

  - pip:
    - flask-cors==3.0.10
    - flask-restful==0.3.9
    - matplotlib==3.6.3
    - networkx==3.0
    - numpy==1.24.1
    - pm4py==2.5.2
    - pandas==1.5.3