name: ocelapp
channels:
  - conda-forge
  - defaults
dependencies:

  - flask=2.2.2
  - graphviz=2.50.0
  - pip=22.3.1
  - pygraphviz=1.9
  - python=3.10.9
  - pip:
    - flask-cors==3.0.10
    - flask-restful==0.3.9
    - matplotlib==3.6.3
    - networkx==3.0
    - numpy==1.24.1
    - pandas==1.5.3
    - pm4py==2.7.0